<?php

include_once('ding_mobile.features.inc');

/**
 * Implementation of hook_menu().
 */
function ding_mobile_menu() {
  $items = array();
    
  $items['user/status'] = array(
    'title' => 'user status',
    'page callback' => 'ding_mobile_forward_to_status',
    'access callback' => true,
  );
  return $items;
}
/*
 * page callback to forward to user loanstatus
 */
function ding_mobile_forward_to_status() {
  global $user;
  if($user->uid){
    drupal_goto('user/' . $user->uid . '/status');
  }
  else{
    drupal_goto('user/login', 'destination=user/status');
  }
}

function ding_mobile_form_ding_reservation_confirm_form_alter(&$form, &$form_state) {  
  $title = $form['object']['#value']->title;
  $form['description']['#value'] = '<h1>'.t('confirm reservation').'</h1><p>'.t('You are about to book %material. Are you sure you want to continue?',array('%material' => $title)).'</p>';
  
  return $form;
}

/**
 * Implementation of hook_ting_object_buttons().
 *
 * Add this reservation button, without javascript pop-up window. The other
 * buttons is hidden in css.
 *
 * TODO: implement remove button functions.
 */
function ding_mobile_ting_object_buttons($object) {
  if (mobile_tools_site_type() == 'mobile') {
    if (!empty($object->localId) && ting_object_is($object, 'reservable')) {
      return l(t('Reserve now'), 'ding/reservation/' . $object->localId, array('attributes' => array('class' => 'reserve-now button'), 'query' => drupal_get_destination()));
    }
  }
}

/**
 * Implementation of hook_theme.
 */
function ding_mobile_theme() {
  return array(
    'ding_mobile_reservation_item_list' => array(
      'arguments' => array(
          'items' => NULL,
          'headline' => NULL,
          'attributes' => NULL
      ),
      'template' => 'ding_mobile_reservation_item_list',
    ),
  );
}

