<?php

include_once('ding_mobile.features.inc');

/**
 * Implementation of hook_menu().
 */
function ding_mobile_menu(){
  $items = array();
    
  $items['user/status'] = array(
    'title' => 'user status',
    'page callback' => 'ding_mobile_forward_to_status',
    'access callback' => true,
  );
  return $items;
}
/*
 * page callback to forward to user loanstatus
 */
function ding_mobile_forward_to_status(){
  global $user;
  if($user->uid){
    drupal_goto('user/'.$user->uid.'/status');
  }
  else{
    drupal_goto('user/login','destination=user/status');
  }
}


function ding_mobile_preprocess_ting_search_collection(&$variables){
  if ($variables['collection']->objects[0] instanceOf TingClientObject) {
    $image_url = ting_covers_collection_url($variables['collection']->objects[0], '80_x');
    if ($image_url) {
      #$variables['picture'] = theme('image', $image_url, '', '', null, false);
    }
  }
}

function ding_mobile_form_ding_reservation_confirm_form_alter(&$form,&$form_state){
  
  #var_dump($form['object']['#value']->title);
  $title = $form['object']['#value']->title;
  $form['description']['#value'] = '<h1>'.t('confirm reservation').'</h1><p>'.t('You are about to book %material. Are you sure you want to continue?',array('%material' => $title)).'</p>';
  
  return $form;
}

/**
 * Implementation of hook_ting_object_buttons().
 */
function ding_mobile_ting_object_buttons($object) {
  if (mobile_tools_site_type() == 'mobile') {
    if (!empty($object->localId) && ting_object_is($object, 'reservable')) {
      return '<button onclick="location.href=\''.url('ding/reservation/' . $object->localId,array('query' => drupal_get_destination(),'absolute' => true)).'\';">'.t('Reserve now').'</button>';
    }
  }
}


